FROM hyperf/hyperf:7.4-alpine-v3.11-swoole
MAINTAINER 89424619@qq.com
COPY file/ping.php /usr/local/bin/ping.php
COPY file/50_swoole_tracker74.ini /etc/php7/conf.d
COPY file/swoole_tracker74.so /usr/lib/php7/modules


